# Generated by Django 2.2.24 on 2021-10-23 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vacancy',
            table='vacancy_vacancy',
        ),
    ]
