# Generated by Django 4.0.4 on 2024-10-01 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='bike',
            name='has_basket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bike',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
    ]
